{% set name = "pep517" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e1ba5dffa3a131387979a68ff3e391ac7d645be409216b961bc2efe6468ab0b2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - flit-core >=2,<3
  run:
    - python
    - importlib_metadata  # [py<38]
    - tomli  # [py>=36]
    - zipp  # [py<38]

test:
  imports:
    - pep517
  commands:
    # temporarily skipping pip check on win and pypy build because of bizarre tqdm issue
    - pip check  # [not (win and python_impl == 'pypy')]
  requires:
    - pip

about:
  home: https://pypi.org/project/pep517/
  summary: Wrappers to build Python packages using PEP 517 hooks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
